- name: Set machine hostname
  hostname:
    name: "{{ ansible_hostname }}"

#- name: Update package list
#  apt:
#    update_cache: yes
#    cache_valid_time: 3600

#- name: Upgrade all packages to the latest version
#  apt:
#    name: "*"
#    state: latest

- name: Install common python packages
  apt:
    name: "{{ item }}"
  loop:
    - git
    - python-pip
    - python-virtualenv
    - libopenjp2-7

- name: Create Python virtualenv
  command: virtualenv pyenv -p python3
  args:
    creates:  "/home/{{ ansible_user }}/pyenv"
  become: no

- name: Add admin user acounts
  user:
    name: "{{item}}"
    state: present
    groups: sudo
  loop: "{{admin_users}}"

- name: install authorized_keys
  authorized_key:
    user: "{{item}}"
    state: present
    key: "{{ lookup('file', 'keys/' + item + '.pub') }}"
  loop: "{{admin_users}}"
